---
- hosts: kubernetes-master-nodes  
#  vars_files:
#  - env_variables
  tasks:
  - name: Downloading Trident install bundle
    get_url: 
      url: http://github.com/NetApp/trident/releases/download/v19.01.0/trident-installer-19.01.0.tar.gz
      dest: /tmp/trident-installer-19.01.0.tar.gz

  - name: Unarchive a file
    unarchive:
      src: /root/trident-installer-19.01.0.tar.gz
      dest: /root
